#!/bin/bash

#Compile lfs chapter 6
#Direct the output to a file for
#later reference in case anything goes wrong

#Run if Tests
function rit(){
   if [[ "$RUN_TESTS" == 1 ]]
   then
      #Run the command given
      $@
   fi
}

#Convenietelly move to the source directory
function cs(){
  cd /sources/
}

cs

#This is where the logs are stored if
#testing is enabled
cl=/sources/logs
mkdir -p $cl

#Previous Exit If Fail. Exits if the previous command returned
#a non-zero status. 
function peif(){
   if [[ "$?" != "0" ]]
   then
      echo ALERT ALERT ALERT ALERT
      echo FAILED AT 
      caller
      exit 1
   fi
}

#6.5 Creating directories
echo -e '\n(6.5-6) Creating directory structure\n'
mkdir -pv /{bin,boot,etc/{opt,sysconfig},home,lib/firmware,mnt,opt}
mkdir -pv /{media/{floppy,cdrom},sbin,srv,var}
install -dv -m 0750 /root
install -dv -m 1777 /tmp /var/tmp
mkdir -pv /usr/{,local/}{bin,include,lib,sbin,src}
mkdir -pv /usr/{,local/}share/{color,dict,doc,info,locale,man}
mkdir -v  /usr/{,local/}share/{misc,terminfo,zoneinfo}
mkdir -v  /usr/libexec
mkdir -pv /usr/{,local/}share/man/man{1..8}

case $(uname -m) in
    x86_64) mkdir -v /lib64 ;;
esac

mkdir -v /var/{log,mail,spool}
ln -sv /run /var/run
ln -sv /run/lock /var/lock
mkdir -pv /var/{opt,cache,lib/{color,misc,locate},local}

ln -sv /tools/bin/{bash,cat,dd,echo,ln,pwd,rm,stty} /bin
ln -sv /tools/bin/{install,perl} /usr/bin
ln -sv /tools/lib/libgcc_s.so{,.1} /usr/lib
ln -sv /tools/lib/libstdc++.{a,so{,.6}} /usr/lib
sed 's/tools/usr/' /tools/lib/libstdc++.la > /usr/lib/libstdc++.la
for lib in blkid lzma mount uuid
do
    ln -sv /tools/lib/lib$lib.{a,so*} /usr/lib
    sed 's/tools/usr/' /tools/lib/lib${lib}.la > /usr/lib/lib${lib}.la
done
ln -sv bash /bin/sh

ln -sv /proc/self/mounts /etc/mtab
cat > /etc/passwd <<"EOF"
root:x:0:0:root:/root:/bin/bash
bin:x:1:1:bin:/dev/null:/bin/false
daemon:x:6:6:Daemon User:/dev/null:/bin/false
messagebus:x:18:18:D-Bus Message Daemon User:/var/run/dbus:/bin/false
systemd-bus-proxy:x:72:72:systemd Bus Proxy:/:/bin/false
systemd-journal-gateway:x:73:73:systemd Journal Gateway:/:/bin/false
systemd-journal-remote:x:74:74:systemd Journal Remote:/:/bin/false
systemd-journal-upload:x:75:75:systemd Journal Upload:/:/bin/false
systemd-network:x:76:76:systemd Network Management:/:/bin/false
systemd-resolve:x:77:77:systemd Resolver:/:/bin/false
systemd-timesync:x:78:78:systemd Time Synchronization:/:/bin/false
systemd-coredump:x:79:79:systemd Core Dumper:/:/bin/false
nobody:x:99:99:Unprivileged User:/dev/null:/bin/false
EOF

cat > /etc/group <<"EOF"
root:x:0:
bin:x:1:daemon
sys:x:2:
kmem:x:3:
tape:x:4:
tty:x:5:
daemon:x:6:
floppy:x:7:
disk:x:8:
lp:x:9:
dialout:x:10:
audio:x:11:
video:x:12:
utmp:x:13:
usb:x:14:
cdrom:x:15:
adm:x:16:
messagebus:x:18:
systemd-journal:x:23:
input:x:24:
mail:x:34:
systemd-bus-proxy:x:72:
systemd-journal-gateway:x:73:
systemd-journal-remote:x:74:
systemd-journal-upload:x:75:
systemd-network:x:76:
systemd-resolve:x:77:
systemd-timesync:x:78:
systemd-coredump:x:79:
nogroup:x:99:
users:x:999:
EOF

touch /var/log/{btmp,lastlog,faillog,wtmp}
chgrp -v utmp /var/log/lastlog
chmod -v 664  /var/log/lastlog
chmod -v 600  /var/log/btmp

#6.7 Linux API Headers
echo -e '\n(6.7) Building Linux API Headers'
tar -xf linux-4.12.7.tar.xz
peif
cd linux-4.12.7
peif

make mrproper > /dev/null
peif

make INSTALL_HDR_PATH=dest headers_install > /dev/null
peif
find dest/include \( -name .install -o -name ..install.cmd \) -delete
peif
cp -r dest/include/* /usr/include
peif

cs
\rm -Rf linux-4.12.7
echo -e '(6.7) Done Building Linux API Headers\n'


#6.8 Man-pages
echo -e '\n(6.8) Building Man-pages'
tar -xf man-pages-4.12.tar.xz
peif
cd man-pages-4.12

make install > /dev/null
peif

cs
\rm -Rf man-pages-4.12
echo -e '(6.8) Done Building Man-pages\n'


#6.9 Glibc
echo -e '\n(6.9) Building Glibc'
tar -xf glibc-2.26.tar.xz
peif
cd glibc-2.26
peif

patch -Np1 -i ../glibc-2.26-fhs-1.patch
peif
ln -sfv /tools/lib/gcc /usr/lib
peif

case $(uname -m) in
    i?86)    GCC_INCDIR=/usr/lib/gcc/$(uname -m)-pc-linux-gnu/7.2.0/include
	     ln -sfv ld-linux.so.2 /lib/ld-lsb.so.3
	     ;;
    x86_64) GCC_INCDIR=/usr/lib/gcc/x86_64-pc-linux-gnu/7.2.0/include
	    ln -sfv ../lib/ld-linux-x86-64.so.2 /lib64
	    ln -sfv ../lib/ld-linux-x86-64.so.2 /lib64/ld-lsb-x86-64.so.3
	    ;;
esac

rm -f /usr/include/limits.h
peif

mkdir -v build
peif
cd build
peif

CC="gcc -isystem $GCC_INCDIR -isystem /usr/include" \
  ../configure --prefix=/usr                          \
  --disable-werror                       \
  --enable-kernel=3.2                    \
  --enable-stack-protector=strong        \
  libc_cv_slibdir=/lib > /dev/null
peif
unset GCC_INCDIR

make -j$MAKEJFLAG > /dev/null
peif
rit echo -e '\nTesting glibc'
rit make check 2> $cl/6.9glibc > /dev/null

touch /etc/ld.so.conf
peif
sed '/test-installation/s@$(PERL)@echo not running@' -i ../Makefile
peif

make install > /dev/null
peif

cp -v ../nscd/nscd.conf /etc/nscd.conf
peif
mkdir -pv /var/cache/nscd
peif
install -v -Dm644 ../nscd/nscd.tmpfiles /usr/lib/tmpfiles.d/nscd.conf
peif
install -v -Dm644 ../nscd/nscd.service /lib/systemd/system/nscd.service
peif

mkdir -pv /usr/lib/locale
localedef -i cs_CZ -f UTF-8 cs_CZ.UTF-8
localedef -i de_DE -f ISO-8859-1 de_DE
localedef -i de_DE@euro -f ISO-8859-15 de_DE@euro
localedef -i de_DE -f UTF-8 de_DE.UTF-8
localedef -i en_GB -f UTF-8 en_GB.UTF-8
localedef -i en_HK -f ISO-8859-1 en_HK
localedef -i en_PH -f ISO-8859-1 en_PH
localedef -i en_US -f ISO-8859-1 en_US
localedef -i en_US -f UTF-8 en_US.UTF-8
localedef -i es_MX -f ISO-8859-1 es_MX
localedef -i fa_IR -f UTF-8 fa_IR
localedef -i fr_FR -f ISO-8859-1 fr_FR
localedef -i fr_FR@euro -f ISO-8859-15 fr_FR@euro
localedef -i fr_FR -f UTF-8 fr_FR.UTF-8
localedef -i it_IT -f ISO-8859-1 it_IT
localedef -i it_IT -f UTF-8 it_IT.UTF-8
localedef -i ja_JP -f EUC-JP ja_JP
localedef -i ru_RU -f KOI8-R ru_RU.KOI8-R
localedef -i ru_RU -f UTF-8 ru_RU.UTF-8
localedef -i tr_TR -f UTF-8 tr_TR.UTF-8
localedef -i zh_CN -f GB18030 zh_CN.GB18030

cat > /etc/nsswitch.conf <<"EOF"
# Begin /etc/nsswitch.conf

passwd: files
group: files
shadow: files

hosts: files dns
networks: files

protocols: files
services: files
ethers: files
rpc: files

# End /etc/nsswitch.conf
EOF
peif

tar -xf ../../tzdata2017b.tar.gz

ZONEINFO=/usr/share/zoneinfo
mkdir -pv $ZONEINFO/{posix,right}

for tz in etcetera southamerica northamerica europe africa antarctica  \
		   asia australasia backward pacificnew systemv; do
    zic -L /dev/null   -d $ZONEINFO       -y "sh yearistype.sh" ${tz}
    zic -L /dev/null   -d $ZONEINFO/posix -y "sh yearistype.sh" ${tz}
    zic -L leapseconds -d $ZONEINFO/right -y "sh yearistype.sh" ${tz}
done

cp -v zone.tab zone1970.tab iso3166.tab $ZONEINFO
zic -d $ZONEINFO -p America/New_York
unset ZONEINFO

ln -sfv /usr/share/zoneinfo/US/Pacific /etc/localtime

echo -e '/usr/local/lib\n/opt/lib\ninclude /etc/ld.so.conf.d/*.conf' > \
     /etc/ld.so.conf
peif
mkdir -pv /etc/ld.so.conf.d

cs
\rm -Rf glibc-2.26
echo -e '(6.9) Done Building Glibc\n'


#6.10 Adjust toolchain
echo -e '\n(6.10) Adjusting Toolchain'

mv -v /tools/bin/{ld,ld-old}
peif
mv -v /tools/$(uname -m)-pc-linux-gnu/bin/{ld,ld-old}
peif
mv -v /tools/bin/{ld-new,ld}
peif
ln -sv /tools/bin/ld /tools/$(uname -m)-pc-linux-gnu/bin/ld
peif

echo -e '\nGcc dumpspects output: '
gcc -dumpspecs | sed -e 's@/tools@@g'                   \
		     -e '/\*startfile_prefix_spec:/{n;s@.*@/usr/lib/ @}' \
		     -e '/\*cpp:/{n;s@$@ -isystem /usr/include@}' >      \
		     `dirname $(gcc --print-libgcc-file-name)`/specs
peif

#Testing compiler
echo 'int main(){}' > dummy.c
cc dummy.c -v -Wl,--verbose &> dummy.log
readelf -l a.out | grep ': /lib'
peif

echo -e '\nCompiler log output: '
grep -o '/usr/lib.*/crt[1in].*succeeded' dummy.log
grep -B1 '^ /usr/include' dummy.log
grep 'SEARCH.*/usr/lib' dummy.log |sed 's|; |\n|g'
grep "/lib.*/libc.so.6 " dummy.log
grep found dummy.log
rm dummy.c a.out dummy.log
echo -e '(6.10) Done adjusting the toolchain\n'


#6.11 Zlib
echo -e '\n(6.11) Building zlib'
tar -xf zlib-1.2.11.tar.xz
peif
cd zlib-1.2.11
peif

./configure --prefix=/usr > /dev/null
peif
make -j$MAKEJFLAG > /dev/null
peif
rit make check 2> $cl/6.11zlib > /dev/null
make install > /dev/null
peif

mv -v /usr/lib/libz.so.* /lib
peif
ln -sfv ../../lib/$(readlink /usr/lib/libz.so) /usr/lib/libz.so
peif

cs
\rm -Rf zlib-1.2.11
peif
echo -e '(6.11) Done Building Zlib\n'


#6.12 File
echo -e '\n(6.12) Building File'
tar -xf file-5.31.tar.gz
peif
cd file-5.31
peif

./configure --prefix=/usr > /dev/null
peif
make -j$MAKEJFLAG > /dev/null
peif
rit make check 2> $cl/6.12file > /dev/null
make install > /dev/null
peif

cs
\rm -Rf file-5.31
echo -e '(6.12) Done Building File\n'


#6.13 Readline
echo -e '\n(6.13) Building Readline'
tar -xf readline-7.0.tar.gz
peif
cd readline-7.0
peif

sed -i '/MV.*old/d' Makefile.in
peif
sed -i '/{OLDSUFF}/c:' support/shlib-install
peif

./configure --prefix=/usr    \
	    --disable-static \
	    --docdir=/usr/share/doc/readline-7.0 > /dev/null
peif
make SHLIB_LIBS="-L/tools/lib -lncursesw" > /dev/null
peif
make SHLIB_LIBS="-L/tools/lib -lncurses" install > /dev/null
peif

mv -v /usr/lib/lib{readline,history}.so.* /lib
peif
ln -sfv ../../lib/$(readlink /usr/lib/libreadline.so) /usr/lib/libreadline.so
peif
ln -sfv ../../lib/$(readlink /usr/lib/libhistory.so ) /usr/lib/libhistory.so
peif

cs
\rm -Rf readline-7.0
echo -e '(6.13) Done Building Readline'


#6.14 m4
echo -e '\n(6.14) Building m4'
tar -xf m4-1.4.18.tar.xz
peif
cd m4-1.4.18
peif

./configure --prefix=/usr > /dev/null
peif
make -j$MAKEJFLAG > /dev/null
peif
make install > /dev/null
peif

cs
\rm -Rf m4-1.4.18
echo -e '(6.14) Done Building m4\n'


#6.15 bc
echo -e '(6.15) Building bc'
tar -xf bc-1.07.1.tar.gz
peif
cd bc-1.07.1
peif

cat > bc/fix-libmath_h <<"EOF"
#! /bin/bash
sed -e '1   s/^/{"/' \
    -e     's/$/",/' \
    -e '2,$ s/^/"/'  \
    -e   '$ d'       \
    -i libmath.h

sed -e '$ s/$/0}/' \
    -i libmath.h
EOF

ln -sv /tools/lib/libncursesw.so.6 /usr/lib/libncursesw.so.6
peif
ln -sfv libncurses.so.6 /usr/lib/libncurses.so
peif

sed -i -e '/flex/s/as_fn_error/: ;; # &/' configure
peif

./configure --prefix=/usr           \
	    --with-readline         \
	    --mandir=/usr/share/man \
	    --infodir=/usr/share/info > /dev/null
peif
make -j$MAKEJFLAG > /dev/null
peif
rit echo "quit" | ./bc/bc -l Test/checklib.b 2> $cl/6.15bc > /dev/null
make install > /dev/null
peif

cs
\rm -Rf bc-1.07.1
echo -e '(6.15) Done Building bc'


#6.16 Binutils
echo -e '\n(6.16) Building Binutils'
tar -xf binutils-2.29.tar.bz2
peif
cd binutils-2.29
peif

expect -c "spawn ls" | grep spawn
peif

mkdir build
cd build
peif

../configure --prefix=/usr       \
	     --enable-gold       \
	     --enable-ld=default \
	     --enable-plugins    \
	     --enable-shared     \
	     --disable-werror    \
	     --with-system-zlib > /dev/null
peif
make tooldir=/usr -j$MAKEJFLAG > /dev/null
peif
rit make -k check 2> $cl/6.16binutils > /dev/null
make tooldir=/usr install > /dev/null
peif

cs
\rm -Rf binutils-2.29
echo -e '(6.16) Done Building Binutils\n'


#6.17 gmp
echo -e '\n(6.17) Building GMP'
tar -xf gmp-6.1.2.tar.xz
peif
cd gmp-6.1.2
peif

./configure --prefix=/usr    \
	   --enable-cxx     \
	   --disable-static \
	   --docdir=/usr/share/doc/gmp-6.1.2 > /dev/null
peif
make -j$MAKEJFLAG > /dev/null
peif
rit make check 2> $cl/6.17gmp > /dev/null
awk '/# PASS:/{total+=$3} ; END{print total}' gmp-check-log
make install > /dev/null
peif

cs
\rm -Rf gmp-6.1.2
echo -e '(6.18) Done Building GMP'


#6.18 MPFR
echo -e '\n(6.18) Building MPFR'
tar -xf mpfr-3.1.5.tar.xz
peif
cd mpfr-3.1.5
peif

./configure --prefix=/usr        \
	    --disable-static     \
	    --enable-thread-safe \
	    --docdir=/usr/share/doc/mpfr-3.1.5 > /dev/null
peif
make -j$MAKEJFLAG > /dev/null
peif
rit make check 2> $cl/6.18mpfr > /dev/null
make install > /dev/null
peif

cs
\rm -Rf mpfr-3.1.5
echo -e '(6.18) Done Building MPFR\n'


#6.19 MPC
echo -e '\n(6.19) Building MPC'
tar -xf mpc-1.0.3.tar.gz
peif
cd mpc-1.0.3
peif

./configure --prefix=/usr    \
	    --disable-static \
	    --docdir=/usr/share/doc/mpc-1.0.3 > /dev/null
peif
make -j$MAKEJFLAG > /dev/null
peif
rit make check 2> $cl/6.19mpc > /dev/null
make install > /dev/null
peif

cs
\rm -Rf mpc-1.0.3
peif
echo -e '(6.19) Done Building MPC\n'


#6.20 GCC
echo -e '\n(6.20) Building GCC'
tar -xf gcc-7.2.0.tar.xz
peif
cd gcc-7.2.0
peif

case $(uname -m) in
    x86_64)
	sed -e '/m64=/s/lib64/lib/' \
	    -i.orig gcc/config/i386/t-linux64
	;;
esac

rm -f /usr/lib/gcc
mkdir build
cd build
peif

SED=sed                               \
../configure --prefix=/usr            \
   --enable-languages=c,c++ \
   --disable-multilib       \
   --disable-bootstrap      \
   --with-system-zlib > /dev/null
peif
make -j$MAKEJFLAG > /dev/null
peif
ulimit -s 32768
rit make -k check 2> $cl/6.20gcc > /dev/null
rit ../contrib/test_summary >> $cl/6.20gcc
make install > /dev/null
peif

ln -sv ../usr/bin/cpp /lib
ln -sv gcc /usr/bin/cc
install -v -dm755 /usr/lib/bfd-plugins
ln -sfv ../../libexec/gcc/$(gcc -dumpmachine)/7.2.0/liblto_plugin.so \
   /usr/lib/bfd-plugins/

#Test compiler
echo 'int main(){}' > dummy.c
cc dummy.c -v -Wl,--verbose &> dummy.log
readelf -l a.out | grep ': /lib'
grep -o '/usr/lib.*/crt[1in].*succeeded' dummy.log
grep -B4 '^ /usr/include' dummy.log
grep 'SEARCH.*/usr/lib' dummy.log |sed 's|; |\n|g'
grep "/lib.*/libc.so.6 " dummy.log
grep found dummy.log
rm dummy.c a.out dummy.log
mkdir -pv /usr/share/gdb/auto-load/usr/lib
mv -v /usr/lib/*gdb.py /usr/share/gdb/auto-load/usr/lib

cs
\rm -Rf gcc-7.2.0
peif
echo -e '(6.20) Done Building GCC\n'


#6.21 Bzip2
echo -e '\n(6.21) Building Bzip2'
tar -xf bzip2-1.0.6.tar.gz
peif
cd bzip2-1.0.6
peif

patch -Np1 -i ../bzip2-1.0.6-install_docs-1.patch
peif
sed -i 's@\(ln -s -f \)$(PREFIX)/bin/@\1@' Makefile
peif
sed -i "s@(PREFIX)/man@(PREFIX)/share/man@g" Makefile
peif

make -f Makefile-libbz2_so > /dev/null
peif
make clean > /dev/null
peif
make -j$MAKEJFLAG > /dev/null
peif
make PREFIX=/usr install > /dev/null
peif

cp -v bzip2-shared /bin/bzip2
cp -av libbz2.so* /lib
ln -sv ../../lib/libbz2.so.1.0 /usr/lib/libbz2.so
rm -v /usr/bin/{bunzip2,bzcat,bzip2}
ln -sv bzip2 /bin/bunzip2
ln -sv bzip2 /bin/bzcat

cs
\rm -Rf bzip2-1.0.6
peif
echo -e '(6.21) Done Building Bzip2\n'


#6.22 Pkg-config
echo -e '\n(6.22) Building Pkg-config'
tar -xf pkg-config-0.29.2.tar.gz
peif
cd pkg-config-0.29.2
peif

./configure --prefix=/usr              \
	    --with-internal-glib       \
	    --disable-host-tool        \
	    --docdir=/usr/share/doc/pkg-config-0.29.2 > /dev/null
peif
make -j$MAKEJFLAG > /dev/null
peif
rit make check 2> $cl/6.22pkgconfig > /dev/null
make install > /dev/null
peif

cs
\rm -Rf pkg-config-0.29.2
peif
echo -e '(6.22) Done Building pkg-config\n'


#6.23 Ncurses
echo -e '\n(6.23) Building Nucrses'
tar -xf ncurses-6.0.tar.gz
peif
cd ncurses-6.0
peif

sed -i '/LIBTOOL_INSTALL/d' c++/Makefile.in
peif

./configure --prefix=/usr           \
	    --mandir=/usr/share/man \
	    --with-shared           \
	    --without-debug         \
	    --without-normal        \
	    --enable-pc-files       \
	    --enable-widec > /dev/null
peif
make -j$MAKEJFLAG > /dev/null
peif
make install > /dev/null
peif

mv -v /usr/lib/libncursesw.so.6* /lib
ln -sfv ../../lib/$(readlink /usr/lib/libncursesw.so) /usr/lib/libncursesw.so
for lib in ncurses form panel menu ; do
    rm -vf                    /usr/lib/lib${lib}.so
    echo "INPUT(-l${lib}w)" > /usr/lib/lib${lib}.so
    ln -sfv ${lib}w.pc        /usr/lib/pkgconfig/${lib}.pc
done
rm -vf                     /usr/lib/libcursesw.so
echo "INPUT(-lncursesw)" > /usr/lib/libcursesw.so
ln -sfv libncurses.so      /usr/lib/libcurses.so

cs
\rm -Rf ncurses-6.0
peif
echo -e '(6.24) Done Building Ncurses\n'


#6.24 Attr
echo -e '\n(6.24) Building Attr'
tar -xf attr-2.4.47.src.tar.gz
peif
cd attr-2.4.47
peif

sed -i -e 's|/@pkg_name@|&-@pkg_version@|' include/builddefs.in
peif
sed -i -e "/SUBDIRS/s|man[25]||g" man/Makefile
peif
sed -i 's:{(:\\{(:' test/run
peif

./configure --prefix=/usr \
	    --disable-static > /dev/null
peif
make -j$MAKEJFLAG > /dev/null
peif
rit make -j1 tests root-tests 2> $cl/6.24attr > /dev/null
make install install-dev install-lib > /dev/null
peif
chmod -v 755 /usr/lib/libattr.so
peif

mv -v /usr/lib/libattr.so.* /lib
ln -sfv ../../lib/$(readlink /usr/lib/libattr.so) /usr/lib/libattr.so

cs
\rm -Rf attr-2.4.47
peif
echo -e '(6.24) Done Building Attr\n'


#6.25 Acl
echo -e '\n(6.25) Building Acl'
tar -xf acl-2.2.52.src.tar.gz
peif
cd acl-2.2.52
peif

sed -i -e 's|/@pkg_name@|&-@pkg_version@|' include/builddefs.in
sed -i "s:| sed.*::g" test/{sbits-restore,cp,misc}.test
sed -i 's/{(/\\{(/' test/run
sed -i -e "/TABS-1;/a if (x > (TABS-1)) x = (TABS-1);" \
    libacl/__acl_to_any_text.c

./configure --prefix=/usr    \
	    --disable-static \
	    --libexecdir=/usr/lib > /dev/null
peif
make -j$MAKEJFLAG > /dev/null
peif
make install install-dev install-lib > /dev/null
peif
chmod -v 755 /usr/lib/libacl.so
peif
mv -v /usr/lib/libacl.so.* /lib
ln -sfv ../../lib/$(readlink /usr/lib/libacl.so) /usr/lib/libacl.so

cs
\rm -Rf acl-2.2.52
peif
echo -e '(6.25) Done Building ACL\n'


#6.26 Libcap
echo -e '\n(6.26) Building Libcap'
tar -xf libcap-2.25.tar.xz
peif
cd libcap-2.25
peif

sed -i '/install.*STALIBNAME/d' libcap/Makefile
peif

make -j$MAKEJFLAG > /dev/null
peif
make RAISE_SETFCAP=no lib=lib prefix=/usr install > /dev/null
peif
chmod -v 755 /usr/lib/libcap.so
peif

mv -v /usr/lib/libcap.so.* /lib
peif
ln -sfv ../../lib/$(readlink /usr/lib/libcap.so) /usr/lib/libcap.so
peif

cs
\rm -Rf libcap-2.25
peif
echo -e '(6.26) Done Building Libcap\n'


#6.27 Sed
echo -e '\n(6.27) Building Sed'
tar -xf sed-4.4.tar.xz
peif
cd sed-4.4
peif

sed -i 's/usr/tools/'                 build-aux/help2man
sed -i 's/testsuite.panic-tests.sh//' Makefile.in

./configure --prefix=/usr --bindir=/bin > /dev/null
peif
make -j$MAKEJFLAG > /dev/null
peif
make install > /dev/null
peif

cs
\rm -Rf sed-4.4
peif
echo -e '(6.27) Done Building Sed\n'


#6.28 Shadow
echo -e '\n(6.28) Building Shadow'
tar -xf shadow-4.5.tar.xz
peif
cd shadow-4.5
peif

sed -i 's/groups$(EXEEXT) //' src/Makefile.in
find man -name Makefile.in -exec sed -i 's/groups\.1 / /'   {} \;
find man -name Makefile.in -exec sed -i 's/getspnam\.3 / /' {} \;
find man -name Makefile.in -exec sed -i 's/passwd\.5 / /'   {} \;
sed -i -e 's@#ENCRYPT_METHOD DES@ENCRYPT_METHOD SHA512@' \
           -e 's@/var/spool/mail@/var/mail@' etc/login.defs
sed -i 's/1000/999/' etc/useradd

./configure --sysconfdir=/etc --with-group-name-max-length=32 > /dev/null
peif
make -j$MAKEJFLAG > /dev/null
peif
make install > /dev/null
peif
mv -v /usr/bin/passwd /bin

pwconv
grpconv

cs
\rm -Rf shadow-4.5
peif
echo -e '(6.28) Done building Shadow\n'


#6.29 psmisc
echo -e '\n(6.29) Building psmisc'
tar -xf psmisc-23.1.tar.xz
peif
cd psmisc-23.1
peif

./configure --prefix=/usr > /dev/null
peif
make -j$MAKEJFLAG > /dev/null
peif
make install > /dev/null
peif
mv -v /usr/bin/fuser   /bin
mv -v /usr/bin/killall /bin

cs
\rm -Rf psmisc-23.1
peif
echo -e '(6.29) Done Building psmisc\n'


#6.30 iana-etc
echo -e '\n(6.30) Building iana-etc'
tar -xf iana-etc-2.30.tar.bz2
peif
cd iana-etc-2.30
peif

make -j$MAKEJFLAG > /dev/null
peif
make install > /dev/null
peif

cs
\rm -Rf iana-etc-2.30
peif
echo -e '(6.30) Done building iana-etc\n'


#6.31 Bison
echo -e '\n(6.31) Building Bison'
tar -xf bison-3.0.4.tar.xz
peif
cd bison-3.0.4
peif

./configure --prefix=/usr --docdir=/usr/share/doc/bison-3.0.4 > /dev/null
peif
make -j$MAKEJFLAG > /dev/null
peif
make install > /dev/null
peif

cs
\rm -Rf bison-3.0.4
peif
echo -e '(6.31) Done Building Bison\n'


#6.32 Flex
echo -e '\n(6.32) Building Flex'
tar -xf flex-2.6.4.tar.gz
peif
cd flex-2.6.4
peif

sed -i "/math.h/a #include <malloc.h>" src/flexdef.h
peif
HELP2MAN=/tools/bin/true \
./configure --prefix=/usr --docdir=/usr/share/doc/flex-2.6.4 > /dev/null
peif
make -j$MAKEJFLAG > /dev/null
peif
rit make check 2> $cl/6.32flex > /dev/null
make install > /dev/null
peif
ln -sv flex /usr/bin/lex

cs
\rm -Rf flex-2.6.4
peif
echo -e '(6.32) Done Building Flex\n'


#6.33 Grep
echo -e '\n(6.33) Building Grep'
tar -xf grep-3.1.tar.xz
peif
cd grep-3.1
peif

./configure --prefix=/usr --bindir=/bin > /dev/null
peif
make -j$MAKEJFLAG > /dev/null
peif
rit make check 2> $cl/6.33grep > /dev/null
make install > /dev/null
peif

cs
\rm -Rf grep-3.1
peif
echo -e '(6.33) Done building Grep\n'


#6.34 Bash
echo -e '\n(6.34) Building BASH'
tar -xf bash-4.4.tar.gz
peif
cd bash-4.4
peif

patch -Np1 -i ../bash-4.4-upstream_fixes-1.patch
peif
./configure --prefix=/usr                       \
	    --docdir=/usr/share/doc/bash-4.4 \
	    --without-bash-malloc               \
	    --with-installed-readline > /dev/null
peif
make -j$MAKEJFLAG > /dev/null
peif
chown -R nobody .
rit su nobody -s /bin/bash -c "PATH=$PATH make tests" 2> $cl/6.24bash > /dev/null
make install > /dev/null
peif
mv -vf /usr/bin/bash /bin

cs
\rm -Rf bash-4.4
peif
echo -e '(6.34) Done Building Bash\n'


#6.35 Libtool
echo -e '\n(6.35) Building Libtool'
tar -xf libtool-2.4.6.tar.xz
peif
cd libtool-2.4.6
peif

./configure --prefix=/usr > /dev/null
peif
make -j$MAKEJFLAG > /dev/null
peif
rit make check 2> $cl/6.35libtool > /dev/null
make install > /dev/null
peif

cs
\rm -Rf libtool-2.4.6
peif
echo -e '(6.35) Done Building Libtool\n'


#6.36 GDBM
echo -e '\n(6.36) Building GDBM'
tar -xf gdbm-1.13.tar.gz
peif
cd gdbm-1.13
peif

./configure --prefix=/usr \
	    --disable-static \
	    --enable-libgdbm-compat > /dev/null
peif
make -j$MAKEJFLAG > /dev/null
peif
rit make check 2> $cl/6.36gdbm > /dev/null
make install > /dev/null
peif

cs
\rm -Rf gdbm-1.13
peif
echo -e '(6.36) Done Building GDBM\n'


#6.37 Gperf
echo -e '\n(6.37) Building Gperf'
tar -xf gperf-3.1.tar.gz
peif
cd gperf-3.1
peif

./configure --prefix=/usr --docdir=/usr/share/doc/gperf-3.1 > /dev/null
peif
make -j$MAKEJFLAG > /dev/null
peif
rit make -j1 check 2> $cl/6.37gperf > /dev/null
make install > /dev/null
peif

cs
\rm -Rf gperf-3.1
peif
echo -e '(6.37) Done Building Gperf\n'


#6.38 Expat
echo -e '\n(6.38) Building Expat'
tar -xf expat-2.2.3.tar.bz2
peif
cd expat-2.2.3
peif

sed -i 's|usr/bin/env |bin/|' run.sh.in
./configure --prefix=/usr --disable-static > /dev/null
peif
make -j$MAKEJFLAG > /dev/null
peif
rit make check 2> $cl/6.38expat > /dev/null
make install > /dev/null
peif

cs
\rm -Rf expat-2.2.3
peif
echo -e '(6.38) Done Building Expat\n'


#6.39 Inetutils
echo -e '\n(6.39) Building Inetutils'
tar -xf inetutils-1.9.4.tar.xz
peif
cd inetutils-1.9.4
peif

./configure --prefix=/usr        \
	    --localstatedir=/var \
	    --disable-logger     \
	    --disable-whois      \
	    --disable-rcp        \
	    --disable-rexec      \
	    --disable-rlogin     \
	    --disable-rsh        \
	    --disable-servers > /dev/null
peif
make -j$MAKEJFLAG > /dev/null
peif
rit make check 2> $cl/6.39inetutils > /dev/null
make install > /dev/null
peif
mv -v /usr/bin/{hostname,ping,ping6,traceroute} /bin
mv -v /usr/bin/ifconfig /sbin

cs
\rm -Rf inetutils-1.9.4
peif
echo -e '(6.39) Done Building inetutils\n'


#6.40 Perl
echo -e '\n(6.40) Building Perl'
tar -xf perl-5.26.0.tar.xz
peif
cd perl-5.26.0
peif

echo "127.0.0.1 localhost $(hostname)" > /etc/hosts
export BUILD_ZLIB=False
export BUILD_BZIP2=0

sh Configure -des -Dprefix=/usr                 \
   -Dvendorprefix=/usr           \
   -Dman1dir=/usr/share/man/man1 \
   -Dman3dir=/usr/share/man/man3 \
   -Dpager="/usr/bin/less -isR"  \
   -Duseshrplib                  \
   -Dusethreads > /dev/null
peif
make -j$MAKEJFLAG > /dev/null
peif
rit make -k test 2> $cl/6.40perl > /dev/null
make install > /dev/null
peif
unset BUILD_ZLIB BUILD_BZIP2

cs
\rm -Rf perl-5.26.0
peif
echo -e '(6.40) Done Building Perl\n'


#6.41 XML::Parser
echo -e '\n(6.41) Building XML::Parser'
tar -xf XML-Parser-2.44.tar.gz
peif
cd XML-Parser-2.44
peif

perl Makefile.PL > /dev/null
peif
make -j$MAKEJFLAG > /dev/null
peif
rit make test 2> $cl/6.41xmlparser > /dev/null
make install > /dev/null
peif

cs
\rm -Rf XML-Parser-2.44
peif
echo -e '(6.41) Done Building XML::Parser\n'


#6.42 intltool
echo -e '\n(6.42) Building Intltool'
tar -xf intltool-0.51.0.tar.gz
peif
cd intltool-0.51.0
peif

sed -i 's:\\\${:\\\$\\{:' intltool-update.in
./configure --prefix=/usr > /dev/null
peif
make -j$MAKEJFLAG > /dev/null
peif
rit make check 2> $cl/6.42intltool > /dev/null
make install > /dev/null
peif
install -v -Dm644 doc/I18N-HOWTO /usr/share/doc/intltool-0.51.0/I18N-HOWTO

cs
\rm -Rf intltool-0.51.0
peif
echo -e '(6.42) Done Building intltool\n'


#6.43 Autoconf
echo -e '\n(6.43) Building Autoconf'
tar -xf autoconf-2.69.tar.xz
peif
cd autoconf-2.69
peif

./configure --prefix=/usr > /dev/null
peif
make -j$MAKEJFLAG > /dev/null
peif
rit make check 2> $cl/6.43autoconf > /dev/null
make install > /dev/null
peif

cs
\rm -Rf autoconf-2.69
peif
echo -e '(6.43) Done Building Autoconf'


#6.44 Automake
echo -e '\n(6.44) Building Automake'
tar -xf automake-1.15.1.tar.xz
peif
cd automake-1.15.1
peif

./configure --prefix=/usr --docdir=/usr/share/doc/automake-1.15.1 > /dev/null
peif
make -j$MAKEJFLAG > /dev/null
peif
sed -i "s:./configure:LEXLIB=/usr/lib/libfl.a &:" t/lex-{clean,depend}-cxx.sh
rit make -j4 check 2> $cl/6.44automake > /dev/null
make install > /dev/null
peif

cs
\rm -Rf automake-1.15.1
peif
echo -e '(6.44) Done Building Automake\n'


#6.45 XZ
echo -e '\n(6.45) Building Xz'
tar -xf xz-5.2.3.tar.xz
peif
cd xz-5.2.3
peif

./configure --prefix=/usr    \
	    --disable-static \
	    --docdir=/usr/share/doc/xz-5.2.3 > /dev/null
peif
make -j$MAKEJFLAG > /dev/null
peif
rit make check 2> $cl/6.45xz > /dev/null
make install > /dev/null
peif
mv /usr/bin/{lzma,unlzma,lzcat,xz,unxz,xzcat} /bin
mv /usr/lib/liblzma.so.* /lib
ln -sf ../../lib/$(readlink /usr/lib/liblzma.so) /usr/lib/liblzma.so

cs
\rm -Rf xz-5.2.3
peif
echo -e '(6.45) Done Building Xz\n'


#6.46 Kmod
echo -e '\n(6.46) Building Kmod'
tar -xf kmod-24.tar.xz
peif
cd kmod-24
peif

./configure --prefix=/usr          \
	    --bindir=/bin          \
	    --sysconfdir=/etc      \
	    --with-rootlibdir=/lib \
	    --with-xz              \
	    --with-zlib > /dev/null
peif
make -j$MAKEJFLAG > /dev/null
peif
make install > /dev/null
peif
for target in depmod insmod lsmod modinfo modprobe rmmod; do
    ln -sfv ../bin/kmod /sbin/$target
done
ln -sfv kmod /bin/lsmod

cs
\rm -Rf kmod-24
peif
echo -e '(6.46) Done Building Kmod\n'


#6.47 Building Gettext
echo -e '\n(6.47) Building Gettext'
tar -xf gettext-0.19.8.1.tar.xz
peif
cd gettext-0.19.8.1
peif

sed -i '/^TESTS =/d' gettext-runtime/tests/Makefile.in &&
sed -i 's/test-lock..EXEEXT.//' gettext-tools/gnulib-tests/Makefile.in

./configure --prefix=/usr    \
	    --disable-static \
	    --docdir=/usr/share/doc/gettext-0.19.8.1 > /dev/null
peif
make -j$MAKEJFLAG > /dev/null
peif
rit make check 2> $cl/6.47gettext > /dev/null
make install > /dev/null
peif
chmod -v 0755 /usr/lib/preloadable_libintl.so

cs
\rm -Rf gettext-0.19.8.1
peif
echo -e '(6.47) Done Building Gettext\n'


#6.48 Systemd
echo -e '\n(6.48) Building systemd'
tar -xf systemd-234-lfs.tar.xz
peif
cd systemd-234-lfs
peif

cat > config.cache <<"EOF"
KILL=/bin/kill
MOUNT_PATH=/bin/mount
UMOUNT_PATH=/bin/umount
HAVE_BLKID=1
BLKID_LIBS="-lblkid"
BLKID_CFLAGS="-I/tools/include/blkid"
HAVE_LIBMOUNT=1
MOUNT_LIBS="-lmount"
MOUNT_CFLAGS="-I/tools/include/libmount"
cc_cv_CFLAGS__flto=no
SULOGIN="/sbin/sulogin"
GPERF_LEN_TYPE=size_t
XSLTPROC="/usr/bin/xsltproc"
EOF

./configure --prefix=/usr            \
	    --sysconfdir=/etc        \
	    --localstatedir=/var     \
	    --config-cache           \
	    --with-rootprefix=       \
	    --with-rootlibdir=/lib   \
	    --enable-split-usr       \
	    --disable-firstboot      \
	    --disable-ldconfig       \
	    --disable-sysusers       \
	    --without-python         \
	    --with-default-dnssec=no \
	    --docdir=/usr/share/doc/systemd-234 > /dev/null
peif
make -j$MAKEJFLAG > /dev/null
peif
make install > /dev/null
peif
rm -rfv /usr/lib/rpm
for tool in runlevel reboot shutdown poweroff halt telinit; do
    ln -sfv ../bin/systemctl /sbin/${tool}
done
ln -sfv ../lib/systemd/systemd /sbin/init
systemd-machine-id-setup

cs
\rm -Rf systemd-234
peif
echo -e '(6.48) Done Building Systemd\n'


#6.49 Procps-ng
echo -e '\n(6.49) Building Procps-ng'
tar -xf procps-ng-3.3.12.tar.xz
peif
cd procps-ng-3.3.12
peif

./configure --prefix=/usr                            \
	    --exec-prefix=                           \
	    --libdir=/usr/lib                        \
	    --docdir=/usr/share/doc/procps-ng-3.3.12 \
	    --disable-static                         \
	    --disable-kill                           \
	    --with-systemd > /dev/null
peif
make -j$MAKEJFLAG > /dev/null
sed -i -r 's|(pmap_initname)\\\$|\1|' testsuite/pmap.test/pmap.exp
sed -i '/set tty/d' testsuite/pkill.test/pkill.exp
rm testsuite/pgrep.test/pgrep.exp
rit make check 2> $cl/6.49procpsng > /dev/null
make install > /dev/null
peif

mv -v /usr/lib/libprocps.so.* /lib
ln -sfv ../../lib/$(readlink /usr/lib/libprocps.so) /usr/lib/libprocps.so

cs
\rm -Rf procps-ng-3.3.12
peif
echo -e '(6.49) Done Building procps-ng\n'


#6.50 e2fsprogs
echo -e '\n(6.50) Building e2fsprogs'
tar -xf e2fsprogs-1.43.5.tar.gz
peif
cd e2fsprogs-1.43.5
peif

mkdir build
cd build
peif

LIBS=-L/tools/lib                    \
CFLAGS=-I/tools/include              \
PKG_CONFIG_PATH=/tools/lib/pkgconfig \
../configure --prefix=/usr           \
    --bindir=/bin           \
    --with-root-prefix=""   \
    --enable-elf-shlibs     \
    --disable-libblkid      \
    --disable-libuuid       \
    --disable-uuidd         \
    --disable-fsck > /dev/null
peif
make -j$MAKEJFLAG > /dev/null
peif
ln -sfv /tools/lib/lib{blk,uu}id.so.1 lib
rit make LD_LIBRARY_PATH=/tools/lib check 2> $cl/6.50e2fsprogs > /dev/null
make install > /dev/null
peif
make install-libs > /dev/null
peif
chmod -v u+w /usr/lib/{libcom_err,libe2p,libext2fs,libss}.a
gunzip -v /usr/share/info/libext2fs.info.gz
install-info --dir-file=/usr/share/info/dir /usr/share/info/libext2fs.info

cs
\rm -Rf e2fsprogs-1.43.5
peif
echo -e '(6.50) Done Building e2fsprogs\n'


#6.51 coreutils
echo -e '\n(6.51) Buidling Coreutils'
tar -xf coreutils-8.27.tar.xz
peif
cd coreutils-8.27
peif

patch -Np1 -i ../coreutils-8.27-i18n-1.patch
peif
sed -i '/test.lock/s/^/#/' gnulib-tests/gnulib.mk

FORCE_UNSAFE_CONFIGURE=1 \
./configure \
      --prefix=/usr            \
      --enable-no-install-program=kill,uptime > /dev/null
peif
FORCE_UNSAFE_CONFIGURE=1 make > /dev/null
peif
rit make NON_ROOT_USERNAME=nobody check-root 2> $cl/6.51coreutils > /dev/null
echo "dummy:x:1000:nobody" >> /etc/group
chown -R nobody .
rit su nobody -s /bin/bash -c "PATH=$PATH make RUN_EXPENSIVE_TESTS=yes check" 2> $cl/6.51coreutils > /dev/null
sed -i '/dummy/d' /etc/group
make install > /dev/null
peif

mv -v /usr/bin/{cat,chgrp,chmod,chown,cp,date,dd,df,echo} /bin
mv -v /usr/bin/{false,ln,ls,mkdir,mknod,mv,pwd,rm} /bin
mv -v /usr/bin/{rmdir,stty,sync,true,uname} /bin
mv -v /usr/bin/chroot /usr/sbin
mv -v /usr/share/man/man1/chroot.1 /usr/share/man/man8/chroot.8
sed -i s/\"1\"/\"8\"/1 /usr/share/man/man8/chroot.8
mv -v /usr/bin/{head,sleep,nice,test,\[} /bin

cs
\rm -Rf coreutils-8.27
peif
echo -e '(6.51) Done Building Coreutils\n'


#6.52 Diffutils
echo -e '\n(6.52) Building Diffutils'
tar -xf diffutils-3.6.tar.xz
peif
cd diffutils-3.6
peif

./configure --prefix=/usr > /dev/null
peif
make -j$MAKEJFLAG > /dev/null
peif
rit make check 2> $cl/6.52diffutils > /dev/null
make install > /dev/null
peif

cs
\rm -Rf diffutils-3.6
peif
echo -e '(6.52) Done Building Diffutils\n'


#6.53 Gawk
echo -e '\n(6.53) Building Gawk'
tar -xf gawk-4.1.4.tar.xz
peif
cd gawk-4.1.4
peif

./configure --prefix=/usr > /dev/null
peif
make -j$MAKEJFLAG > /dev/null
peif
rit make check 2> $cl/6.53gawk > /dev/null
make install > /dev/null
peif

cs
\rm -Rf gawk-4.1.4
peif
echo -e '(6.53) Done Building Gawk\n'


#6.54 Findutils
echo -e '\n(6.54) Building Findutils'
tar -xf findutils-4.6.0.tar.gz
peif
cd findutils-4.6.0
peif

sed -i 's/test-lock..EXEEXT.//' tests/Makefile.in
./configure --prefix=/usr --localstatedir=/var/lib/locate > /dev/null
peif
make -j$MAKEJFLAG > /dev/null
peif
rit make check 2> $cl/6.54findutils > /dev/null
make install > /dev/null
peif
mv -v /usr/bin/find /bin
sed -i 's|find:=${BINDIR}|find:=/bin|' /usr/bin/updatedb

cs
\rm -Rf findutils-4.6.0
peif
echo -e '(6.54) Done Building Findutils\n'


#6.55 Groff
echo -e '\n(6.55) Building Groff'
tar -xf groff-1.22.3.tar.gz
peif
cd groff-1.22.3
peif

PAGE=letter ./configure --prefix=/usr > /dev/null
peif
make -j1 > /dev/null
peif
make install > /dev/null
peif

cs
\rm -Rf groff-1.22.3
peif
echo -e '(6.55) Done Building Groff\n'


#6.56 Grub
echo -e '\n(6.56) Building Grub'
tar -xf grub-2.02.tar.xz
peif
cd grub-2.02
peif

./configure --prefix=/usr          \
	    --sbindir=/sbin        \
	    --sysconfdir=/etc      \
	    --disable-efiemu       \
	    --disable-werror > /dev/null
peif
make -j$MAKEJFLAG > /dev/null
peif
make install > /dev/null
peif

cs
\rm -Rf grub-2.02
peif
echo -e '(6.56) Done Building Grub\n'


#6.57 Less
echo -e '\n(6.57) Building Less'
tar -xf less-487.tar.gz
peif
cd less-487
peif

./configure --prefix=/usr --sysconfdir=/etc > /dev/null
peif
make -j$MAKEJFLAG > /dev/null
peif
make install > /dev/null
peif

cs
\rm -Rf less-487
peif
echo -e '(6.57) Done Building Less\n'


#6.58 Gzip
echo -e '\n(6.58) Building Gzip'
tar -xf gzip-1.8.tar.xz
peif
cd gzip-1.8
peif

./configure --prefix=/usr > /dev/null
peif
make -j$MAKEJFLAG > /dev/null
peif
rit make check 2> $cl/6.58gzip > /dev/null
make install > /dev/null
peif
mv -v /usr/bin/gzip /bin

cs
\rm -Rf gzip-1.8
peif
echo -e '(6.58) Done building gzip\n'


#6.59 iproute2
echo -e '\n(6.59) Building iproute2'
tar -xf iproute2-4.12.0.tar.xz
peif
cd iproute2-4.12.0
peif

sed -i /ARPD/d Makefile
sed -i 's/arpd.8//' man/man8/Makefile
rm -v doc/arpd.sgml
sed -i 's/m_ipt.o//' tc/Makefile

make -j$MAKEJFLAG > /dev/null
peif
make DOCDIR=/usr/share/doc/iproute2-4.12.0 install > /dev/null
peif

cs
\rm -Rf iproute2-4.12.0
peif
echo -e '(6.59) Done Building Iproute2\n'


#6.60 Kbd
echo -e '\n(6.60) Building Kbd'
tar -xf kbd-2.0.4.tar.xz
peif
cd kbd-2.0.4
peif

patch -Np1 -i ../kbd-2.0.4-backspace-1.patch
peif
sed -i 's/\(RESIZECONS_PROGS=\)yes/\1no/g' configure
sed -i 's/resizecons.8 //' docs/man/man8/Makefile.in
PKG_CONFIG_PATH=/tools/lib/pkgconfig ./configure --prefix=/usr --disable-vlock > /dev/null
peif
make -j$MAKEJFLAG > /dev/null
peif
rit make check 2> $cl/6.60kbd > /dev/null
make install > /dev/null
peif

cs
\rm -Rf kbd-2.0.4
peif
echo -e '(6.60) Done Building Kbd\n'


#6.61 Libpipeline
echo -e '\n(6.61) Building Libpipeline'
tar -xf libpipeline-1.4.2.tar.gz
peif
cd libpipeline-1.4.2
peif

PKG_CONFIG_PATH=/tools/lib/pkgconfig ./configure --prefix=/usr > /dev/null
peif
make -j$MAKEJFLAG > /dev/null
peif
rit make check 2> $cl/6.61libpipeline > /dev/null
make install > /dev/null
peif

cs
\rm -Rf libpipeline-1.4.2
peif
echo -e '(6.61) Done Building Libpipeline\n'


#6.62 make
echo -e '\n(6.62) Building Make'
tar -xf make-4.2.1.tar.bz2
peif
cd make-4.2.1
peif

./configure --prefix=/usr > /dev/null
peif
make -j$MAKEJFLAG > /dev/null
peif
rit make PERL5LIB=$PWD/tests/ check 2> $cl/6.62make > /dev/null
make install > /dev/null
peif

cs
\rm -Rf make-4.2.1
peif
echo -e '(6.62) Done Building Make\n'


#6.63 patch
echo -e '\n(6.63) Building Patch'
tar -xf patch-2.7.5.tar.xz
peif
cd patch-2.7.5
peif

./configure --prefix=/usr > /dev/null
peif
make -j$MAKEJFLAG > /dev/null
peif
rit make check 2> $cl/6.63patch > /dev/null
make install > /dev/null
peif

cs
\rm -Rf patch-2.7.5
peif
echo -e '(6.63) Done Building Patch\n'


#6.64 D-Bus
echo -e '\n(6.64) Building D-Bus'
tar -xf dbus-1.10.22.tar.gz
peif
cd dbus-1.10.22
peif

./configure --prefix=/usr                       \
	    --sysconfdir=/etc                   \
	    --localstatedir=/var                \
	    --disable-static                    \
	    --disable-doxygen-docs              \
	    --disable-xml-docs                  \
	    --docdir=/usr/share/doc/dbus-1.10.22 \
	    --with-console-auth-dir=/run/console > /dev/null
peif
make -j$MAKEJFLAG > /dev/null
peif
make install > /dev/null
peif
mv -v /usr/lib/libdbus-1.so.* /lib
ln -sfv ../../lib/$(readlink /usr/lib/libdbus-1.so) /usr/lib/libdbus-1.so
ln -sfv /etc/machine-id /var/lib/dbus

cs
\rm -Rf dbus-1.10.22
peif
echo -e '(6.64) Done building Dbus\n'


#6.65 Util-linux
echo -e '\n(6.65) Building Util-linux'
tar -xf util-linux-2.30.1.tar.xz
peif
cd util-linux-2.30.1
peif

mkdir -pv /var/lib/hwclock
./configure ADJTIME_PATH=/var/lib/hwclock/adjtime   \
	    --docdir=/usr/share/doc/util-linux-2.30.1 \
	    --disable-chfn-chsh  \
	    --disable-login      \
	    --disable-nologin    \
	    --disable-su         \
	    --disable-setpriv    \
	    --disable-runuser    \
	    --disable-pylibmount \
	    --disable-static     \
	    --without-python > /dev/null
peif
make -j$MAKEJFLAG > /dev/null
peif
chown -R nobody .
rit su nobody -s /bin/bash -c "PATH=$PATH make -k check" 2> $cl/6.65utillinux > /dev/null
make install > /dev/null
peif

cs
\rm -Rf util-linux-2.30.1
peif
echo -e '(6.65) Done Building Util-linux\n'


#6.66 Man-db
echo -e '\n(6.66) Building Man-db'
tar -xf man-db-2.7.6.1.tar.xz
peif
cd man-db-2.7.6.1
peif

./configure --prefix=/usr                        \
	    --docdir=/usr/share/doc/man-db-2.7.6.1 \
	    --sysconfdir=/etc                    \
	    --disable-setuid                     \
	    --enable-cache-owner=bin             \
	    --with-browser=/usr/bin/lynx         \
	    --with-vgrind=/usr/bin/vgrind        \
	    --with-grap=/usr/bin/grap > /dev/null
peif
make -j$MAKEJFLAG > /dev/null
rit make check 2> $cl/6.66mandb > /dev/null
make install > /dev/null
peif
sed -i "s:man man:root root:g" /usr/lib/tmpfiles.d/man-db.conf

cs
\rm -Rf man-db-2.7.6.1
peif
echo -e '(6.66) Done Building Man-db\n'


#6.67 Tar
echo -e '\n(6.67) Building Tar'
tar -xf tar-1.29.tar.xz
peif
cd tar-1.29
peif

FORCE_UNSAFE_CONFIGURE=1  \
./configure --prefix=/usr \
      --bindir=/bin > /dev/null
peif
make -j$MAKEJFLAG > /dev/null
peif
rit make check 2> $cl/6.67tar > /dev/null
make install > /dev/null
peif
make -C doc install-html docdir=/usr/share/doc/tar-1.29 > /dev/null

cs
\rm -Rf tar-1.29
peif
echo -e '(6.67) Done building Tar\n'


#6.68 texinfo
echo -e '\n(6.68) Building Texinfo'
tar -xf texinfo-6.4.tar.xz
peif
cd texinfo-6.4
peif

./configure --prefix=/usr --disable-static > /dev/null
peif
make -j$MAKEJFLAG > /dev/null
peif
rit make check 2> $cl/6.68texinfo > /dev/null
make install > /dev/null
peif

cs
\rm -Rf texinfo-6.4
peif
echo -e '(6.68) Done Building Texinfo\n'


#6.69 vim
echo -e '\n(6.69) Building vim'
tar -xf vim-8.0.586.tar.bz2
peif
cd vim80
peif

echo '#define SYS_VIMRC_FILE "/etc/vimrc"' >> src/feature.h
sed -i '/call/{s/split/xsplit/;s/303/492/}' src/testdir/test_recover.vim
./configure --prefix=/usr > /dev/null
peif
make -j$MAKEJFLAG > /dev/null
peif
make install > /dev/null
peif
ln -sv vim /usr/bin/vi
for L in  /usr/share/man/{,*/}man1/vim.1; do
    ln -sv vim.1 $(dirname $L)/vi.1
done
ln -sv ../vim/vim80/doc /usr/share/doc/vim-8.0.586

cs
\rm -Rf vim80
peif
echo -e '(6.69) Done Building Vim\n'


#6.71 Strip binaries
save_lib="ld-2.26.so libc-2.26.so libpthread-2.26.so libthread_db-1.0.so"

cd /lib

for LIB in $save_lib; do
    objcopy --only-keep-debug $LIB $LIB.dbg
    strip --strip-unneeded $LIB
    objcopy --add-gnu-debuglink=$LIB.dbg $LIB
done

save_usrlib="libquadmath.so.0.0.0 libstdc++.so.6.0.24
             libmpx.so.2.0.1 libmpxwrappers.so.2.0.1 libitm.so.1.0.0
             libcilkrts.so.5.0.0 libatomic.so.1.2.0"

cd /usr/lib

for LIB in $save_usrlib; do
    objcopy --only-keep-debug $LIB $LIB.dbg
    strip --strip-unneeded $LIB
    objcopy --add-gnu-debuglink=$LIB.dbg $LIB
done

unset LIB save_lib save_usrlib

/tools/bin/find /usr/lib -type f -name \*.a \
		-exec /tools/bin/strip --strip-debug {} ';'

/tools/bin/find /lib /usr/lib -type f \( -name \*.so* -a ! -name \*dbg \) \
		-exec /tools/bin/strip --strip-unneeded {} ';'

/tools/bin/find /{bin,sbin} /usr/{bin,sbin,libexec} -type f \
		-exec /tools/bin/strip --strip-all {} ';'

rm -rf /tmp/*
rm -f /usr/lib/lib{bfd,opcodes}.a
rm -f /usr/lib/libbz2.a
rm -f /usr/lib/lib{com_err,e2p,ext2fs,ss}.a
rm -f /usr/lib/libltdl.a
rm -f /usr/lib/libfl.a
rm -f /usr/lib/libfl_pic.a
rm -f /usr/lib/libz.a

echo -e '(6.71) Done stripping binaries and cleaning up\n'


#Chapter 7 configuration
echo -e '\n(7.x) Configuring system'

mv /SYSTEMD_NET_CONFIG /etc/systemd/network/10-eth0-static.network
peif
mv /RESOLV_CONF /etc/resolv.conf
peif
echo "Linux From Scratch" > /etc/hostname
echo "127.0.0.1 localhost" > /etc/hosts
echo -e '0.0 0 0.0\n0\nLOCAL' > /etc/adjtime
echo "LANG=en_US" > /etc/locale.conf
echo -e 'set bell-style none' > /etc/inputrc
echo -e '/bin/sh\n/bin/bash' > /etc/shells
cs
echo -e '(7.x) Done Configuring the system'


#Linux Kernel
echo -e '\nBuilding Linux Kernel ...'

tar -xf linux-4.12.7.tar.xz
peif
cd linux-4.12.7
peif

make mrproper
mv /LINUX_CONFIG ./.config
make -j$MAKEJFLAG > /dev/null
peif
make install > /dev/null
peif

cs
\rm -Rf linux-4.12.7
peif
echo -e 'Done Building Linux Kernel'

#Set root password
echo "root:$ROOT_PASSWD" | chpasswd
